
package diondekoning.bmicalc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BMICalc.WebService", targetNamespace = "http://diondekoning/BMICalc", wsdlLocation = "file:/Users/Dion/git/V2IAC1/opdracht1/src/BMICalc.wsdl")
public class BMICalcWebService
    extends Service
{

    private final static URL BMICALCWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException BMICALCWEBSERVICE_EXCEPTION;
    private final static QName BMICALCWEBSERVICE_QNAME = new QName("http://diondekoning/BMICalc", "BMICalc.WebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/Dion/git/V2IAC1/opdracht1/src/BMICalc.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BMICALCWEBSERVICE_WSDL_LOCATION = url;
        BMICALCWEBSERVICE_EXCEPTION = e;
    }

    public BMICalcWebService() {
        super(__getWsdlLocation(), BMICALCWEBSERVICE_QNAME);
    }

    public BMICalcWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BMICALCWEBSERVICE_QNAME, features);
    }

    public BMICalcWebService(URL wsdlLocation) {
        super(wsdlLocation, BMICALCWEBSERVICE_QNAME);
    }

    public BMICalcWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BMICALCWEBSERVICE_QNAME, features);
    }

    public BMICalcWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BMICalcWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort() {
        return super.getPort(new QName("http://diondekoning/BMICalc", "WS-Port"), WSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSInterface
     */
    @WebEndpoint(name = "WS-Port")
    public WSInterface getWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://diondekoning/BMICalc", "WS-Port"), WSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BMICALCWEBSERVICE_EXCEPTION!= null) {
            throw BMICALCWEBSERVICE_EXCEPTION;
        }
        return BMICALCWEBSERVICE_WSDL_LOCATION;
    }

}
