
package diondekoning.bmicalc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import diondekoning.bmicalc_request.BMICalcRequest;
import diondekoning.bmicalc_response.BMICalcResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WS-Interface", targetNamespace = "http://diondekoning/BMICalc")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    diondekoning.bmicalc_error.ObjectFactory.class,
    diondekoning.bmicalc_request.ObjectFactory.class,
    diondekoning.bmicalc_response.ObjectFactory.class
})
public interface WSInterface {


    /**
     * 
     * @param parameters
     * @return
     *     returns diondekoning.bmicalc_response.BMICalcResponse
     * @throws ApplicatieFout
     */
    @WebMethod(operationName = "BMICalc")
    @WebResult(name = "BMICalc-response", targetNamespace = "http://diondekoning/BMICalc-response", partName = "response")
    public BMICalcResponse bmiCalc(
        @WebParam(name = "BMICalc-request", targetNamespace = "http://diondekoning/BMICalc-request", partName = "parameters")
        BMICalcRequest parameters)
        throws ApplicatieFout
    ;

}
